kind = "web"
previewPath = "/"
title = "NFT Gift Market"
version = "1.0.0"
id = "artifacts/gift-market"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23287

[services.development]
run = "pnpm --filter @workspace/gift-market run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gift-market", "run", "build" ]
publicDir = "artifacts/gift-market/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23287"
BASE_PATH = "/"
